doctrine_migrations:
    migrations_paths:
        # 'DoctrineMigrations': '%kernel.project_dir%/migrations/landlord'
        'DoctrineMigrations': '%kernel.project_dir%/migrations/tenant'
    enable_profiler: false
