doctrine:
    dbal:
        connections:
            tenant: 
                url: '%env(resolve:TENANT_DATABASE_URL)%'
            landlord: 
                url: '%env(resolve:LANDLORD_DATABASE_URL)%'
        default_connection: tenant

    orm:
        default_entity_manager: tenant
        entity_managers:
            tenant:
                connection: tenant
                mappings:
                    Tenant:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/mapping/tenant'
                        prefix: 'Tenant\Entity'
                        alias: Tenant
            landlord:
                connection: landlord
                mappings:
                    Landlord:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Landlord/Entity'
                        prefix: 'Landlord\Entity'
                        alias: Landlord

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
