security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        chain_provider:
            chain:
                providers: [in_memory, tenant_user]
        tenant_user:
            entity:
                class: Tenant\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    main_admin:
                        password: '%env(MAIN_ADMIN_PASSWORD)%'
                        roles: [ROLE_SUPER_ADMIN]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: chain_provider
            form_login:
                login_path: tenant_login
                check_path: tenant_login
                default_target_path: tenant_sale_order_index
                enable_csrf: true
            logout:
                path: tenant_logout
                target: tenant_login

    access_control:
        - { path: /login, roles: PUBLIC_ACCESS }
        - { path: /, roles: ROLE_USER }
