services:
  web-pos:
    container_name: web-pos
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/var/www/html
    ports:
      - '3000:80'
    networks:
      - pos-network
    depends_on:
      - mysql-pos

  mysql-pos:
    container_name: mysql-pos
    image: mysql:8.2.0
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: landlord
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../db-data:/var/lib/mysql
    networks:
      - pos-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

networks:
  pos-network:
    name: pos-network