controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

app_index:
    path: /{_locale}/
    controller: App\Controller\IndexController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: index/index.html.twig
        _locale: '%locale%'

root_route_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/%locale%/'
        permanent: false

app_login:
    path: /{_locale}/login
    methods: ["GET", "POST"]
    controller: App\Controller\SecurityController::login
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: security/login.html.twig
        _locale: '%locale%'

app_logout:
    path: /{_locale}/logout
    controller: App\Controller\SecurityController::logout
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
