parameters:
    locale: es
    app_locales: en|es

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            string $locales: '%app_locales%'
            string $defaultLocale: '%locale%'

    Tenant\:
        resource: '../src/Tenant/'
        exclude: '../src/Tenant/Entity/'