parameters:
    locale: es
    app_locales: en|es

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            string $locales: '%app_locales%'
            string $defaultLocale: '%locale%'

    Landlord\Command\CreateTenantDbCommand:
        tags:
            - { name: 'console.command', command: 'landlord:create-tenant-db' }

    Landlord\Command\RunMigrationsCommand:
        tags:
            - { name: 'console.command', command: 'landlord:run-migrations' }

    Tenant\:
        resource: '../src/Tenant/'
        exclude: '../src/Tenant/Entity/'

