tenant_login:
    path: /{_locale}/login
    methods: GET|POST
    controller: Tenant\Controller\SecurityController::login
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: security/login.html.twig
        _locale: '%locale%'

tenant_logout:
    path: /{_locale}/logout
    controller: Tenant\Controller\SecurityController::logout
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'