tenant_sale_order_line_add:
    path: /{_locale}/sale-order/{soid}/line-add
    methods: POST
    controller: Tenant\Controller\SaleOrderLineController::addLine
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

tenant_sale_order_line_remove:
    path: /{_locale}/sale-order/{soid}/line-remove/{solid}
    methods: POST
    controller: Tenant\Controller\SaleOrderLineController::removeLine
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'