tenant_sale_order_line_add:
    path: /sale-order/{id}/line-add
    methods: POST
    controller: Tenant\Controller\SaleOrderLineController::addLine

tenant_sale_order_line_remove:
    path: /sale-order/{id}/line-remove/{solid}
    methods: POST
    controller: Tenant\Controller\SaleOrderLineController::removeLine